Sprint 1/gettingstarted/urls.py
from django.urls import path, include

from django.contrib import admin

admin.autodiscover()

import hello.views

# To add a new path, first import the app:
# import blog
#
# Then add the new path:
# path('blog/', blog.urls, name="blog")
#
# Learn more here: https://docs.djangoproject.com/en/2.1/topics/http/urls/

urlpatterns = [
    path("", hello.views.index, name="index"),
    path("db/", hello.views.db, name="db"),
    path("admin/", admin.site.urls),
    path('polls/', include('polls.urls')),
]

Sprint 1/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

Sprint 1/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    # ex: /polls/
    path('', views.index, name='index'),
    # ex: /polls/5/
    path('<int:question_id>/', views.detail, name='detail'),
    # ex: /polls/5/results/
    path('<int:question_id>/results/', views.results, name='results'),
    # ex: /polls/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),
    # ex: /polls/room
    path('room/', views.room, name='room')
]

Sprint 1/hello/models.py
from django.db import models

# Create your models here.
class Greeting(models.Model):
    when = models.DateTimeField("date created", auto_now_add=True)

Sprint 1/polls/models.py
import datetime

from django.db import models
from django.utils import timezone

# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text
    
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

Sprint 1/hello/views.py
from django.shortcuts import render
from django.http import HttpResponse
import requests
from .models import Greeting
import os

# Create your views here.
def index(request):
    times = int(os.environ.get('TIMES',3))
    return HttpResponse('Hello! ' * times)


def db(request):

    greeting = Greeting()
    greeting.save()

    greetings = Greeting.objects.all()

    return render(request, "db.html", {"greetings": greetings})

Sprint 1/polls/views.py
from django.http import Http404
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse
from django.template import loader
from .models import Question
import requests

# Create your views here.
def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    template = loader.get_template('polls/index.html')
    context = {
        'latest_question_list': latest_question_list,
    }
    return render(request, 'polls/index.html', context)

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html', {'question': question})
    '''
    URL = "https://www.googleapis.com/youtube/v3/search"
    key = "AIzaSyBtQEH431JmblFH_MAJpLC9AoyGCCOYC54"
    param1 = "snippet"
    param2 = "cats"
    param3 = "1"
    param4 = "relavance"
    param5 = "video"
    param6 = "true"
    PARAMS = {'key':key, 'part':param1, 'q':param2, 'maxResults':param3, 'order':param4, 'type':param5, 'videoEmbeddable':param6}
    r = requests.get(url=URL, params=PARAMS)
    data = r.json()
    
    for record in data['items']:
        list1 = record['id']['videoId']
    return HttpResponse(list1)
    '''

def results(request, question_id):
    response = "You're looking at the results of question %s."
    return HttpResponse(response % question_id)

def vote(request, question_id):
    return HttpResponse("You're voting on question %s." % question_id)

def room(request):
    return render(request, 'polls/room.html')

Sprint 1/hello/templates/base.html
<!DOCTYPE html>
<html>
<head>
<title>Python Getting Started on Heroku</title>
  <link rel="stylesheet" type="text/css" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css" />
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
  <script type="text/javascript" src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
  <style type="text/css">
    .jumbotron {
        background: #532f8c;
        color: white;
        padding-bottom: 80px
    }
    .jumbotron .btn-primary {
        background: #845ac7;
        border-color: #845ac7
    }
    .jumbotron .btn-primary:hover {
        background: #7646c1
    }
    .jumbotron p {
        color: #d9ccee;
        max-width: 75%;
        margin: 1em auto 2em
    }
    .navbar+.jumbotron {
        margin-top: -20px
    }
    .jumbotron .lang-logo {
        display: block;
        background: #b01302;
        border-radius: 50%;
        overflow: hidden;
        width: 100px;
        height: 100px;
        margin: auto;
        border: 2px solid white
    }
    .jumbotron .lang-logo img {
        max-width: 100%
    }


  </style>
</head>
<body>
<nav class="navbar navbar-default navbar-static-top navbar-inverse">
  <div class="container">
    <ul class="nav navbar-nav">
      <li class="active">
        <a href="/"><span class="glyphicon glyphicon-home"></span> Home</a>
      </li>
      <li>
        <a href="https://devcenter.heroku.com/articles/how-heroku-works"><span class="glyphicon glyphicon-user"></span> How Heroku Works</a>
      </li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><span class="glyphicon glyphicon-info-sign"></span> Getting Started Guides <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="https://devcenter.heroku.com/articles/getting-started-with-ruby">Getting Started with Ruby on Heroku</a></li>
            <li><a href="https://devcenter.heroku.com/articles/getting-started-with-nodejs">Getting Started with Node on Heroku</a></li>
            <li><a href="https://devcenter.heroku.com/articles/getting-started-with-php">Getting Started with PHP on Heroku</a></li>
            <li><a href="https://devcenter.heroku.com/articles/getting-started-with-python">Getting Started with Python on Heroku</a></li>
            <li><a href="https://devcenter.heroku.com/articles/getting-started-with-java">Getting Started with Java on Heroku</a></li>
            <li><a href="https://devcenter.heroku.com/articles/getting-started-with-clojure">Getting Started with Clojure on Heroku</a></li>
            <li><a href="https://devcenter.heroku.com/articles/getting-started-with-scala">Getting Started with Scala on Heroku</a></li>
            <li class="divider"></li>
            <li><a href="https://devcenter.heroku.com/articles/getting-started-with-heroku-and-connect-without-local-dev">Getting Started on Heroku with Heroku Connect</a></li>
            <li><a href="https://devcenter.heroku.com/articles/getting-started-with-jruby">Getting Started with Ruby on Heroku (Microsoft Windows)</a></li>
          </ul>
      </li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li class="navbar-right">
        <a href="https://devcenter.heroku.com"><span class="glyphicon glyphicon-book"></span> Heroku Dev Center</a>
      </li>
    </ul>
  </div>
</nav>

{% block content %}{% endblock %}

</body>
</html>

Sprint 1/hello/templates/db.html
{% extends "base.html" %}
{% load static %}

{% block content %}
  <div class="container">


<h2>Page View Report</h2>


<ul>

{% for greeting in greetings %}
    <li>{{ greeting.when }}</li>
{% endfor %}

</ul>

</div>

{% endblock %}

Sprint 1/hello/templates/index.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<div class="jumbotron text-center">
  <div class="container">
    <a href="/" class="lang-logo">
      <img src="{% static 'lang-logo.png'%}">
    </a>
    <h1>Getting Started with Python on Heroku</h1>
    <p>This is a sample Python application deployed to Heroku. It's a reasonably simple app - but a good foundation for understanding how to get the most out of the Heroku platform.</p>
    <a type="button" class="btn btn-lg btn-default" href="https://devcenter.heroku.com/articles/getting-started-with-python"><span class="glyphicon glyphicon-flash"></span> Getting Started with Python</a>
    <a type="button" class="btn btn-lg btn-primary" href="https://github.com/heroku/python-getting-started"><span class="glyphicon glyphicon-download"></span> Source on GitHub</a>
  </div>
</div>
<div class="container">
  <div class="alert alert-info text-center" role="alert">
    To deploy your own copy, and learn the fundamentals of the Heroku platform, head over to the <a href="https://devcenter.heroku.com/articles/getting-started-with-python" class="alert-link">Getting Started with Python on Heroku</a> tutorial.
  </div>
  <hr>
  <div class="row">
    <div class="col-md-6">
      <h3><span class="glyphicon glyphicon-info-sign"></span> How this sample app works</h3>
      <ul>
        <li>This app was deployed to Heroku, either using Git or by using <a href="https://github.com/heroku/python-getting-started">Heroku Button</a> on the repository.</li>

        <li>When Heroku received the source code, it fetched all the dependencies in <a href="https://github.com/heroku/python-getting-started/blob/main/requirements.txt">requirements.txt</a>, creating a deployable slug.</li>
        <li>The platform then spins up a dyno, a lightweight container that provides an isolated environment in which the slug can be mounted and executed.</li>
        <li>You can scale your app, manage it, and deploy over <a href="https://addons.heroku.com/">150 add-on services</a>, from the Dashboard or CLI.</li>
      </ul>
    </div>
    <div class="col-md-6">
      <h3><span class="glyphicon glyphicon-link"></span> Next Steps</h3>
      <ul>
        <li>If you are following the <a href="https://devcenter.heroku.com/articles/getting-started-with-python">Getting Started</a> guide, then please head back to the tutorial and follow the next steps!</li>
        <li>If you deployed this app by deploying the Heroku Button, then in a command line shell, run:</li>
        <ul>
          <li><code>git clone https://github.com/heroku/python-getting-started.git</code> - this will create a local copy of the source code for the app</li>
          <li><code>cd python-getting-started</code> - change directory into the local source code repository</li>
          <li><code>heroku git:remote -a &lt;your-app-name></code> - associate the Heroku app with the repository</li>
          <li>You'll now be set up to run the app locally, or <a href="https://devcenter.heroku.com/articles/getting-started-with-python#push-local-changes">deploy changes</a> to Heroku</li>
        </ul>
      </ul>
      <h3><span class="glyphicon glyphicon-link"></span> Helpful Links</h3>
      <ul>
        <li><a href="https://www.heroku.com/home">Heroku</a></li>
        <li><a href="https://devcenter.heroku.com/">Heroku Dev Center</a></li>
        <li><a href="https://devcenter.heroku.com/articles/getting-started-with-python">Getting Started with Python on Heroku</a></li>
        <li><a href="https://devcenter.heroku.com/articles/django-app-configuration">Configuring Django Apps for Heroku</a></li>
      </ul>
    </div>
  </div> <!-- row -->
   <div class="alert alert-info text-center" role="alert">
    Please do work through the Getting Started guide, even if you do know how to build such an application.  The guide covers the basics of working with Heroku, and will familiarize you with all the concepts you need in order to build and deploy your own apps.
  </div>
</div>
{% endblock %}

Sprint 1/polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<input type="submit" value="Vote">
</form>

Sprint 1/polls/templates/polls/index.html
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
    <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

Sprint 1/polls/templates/polls/room.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Room</title>
    {% load static %}
    <script src="https://kit.fontawesome.com/72ae810c7a.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'polls/test1.css' %}">
    <script>
      function openSlideMenu() {
        document.getElementById('menu').style.width='250px';
        document.getElementById('content').style.marginLeft='250px';
      }
      function closeSlideMenu() {
        document.getElementById('menu').style.width='0px';
        document.getElementById('content').style.marginLeft='0px';
      }
      function sleep(ms) {
        return new Promise(resolve => setTimeout(resolve, ms));
      }

      var i = 0;
      function move(duration) {
        if (i == 0) {
          i = 1;
          var elem = document.getElementById("myBar");
          var width = 1 / duration;
          var hold = width;
          var id = setInterval(frame, 10);
          function frame() {
            if (hold >= 100) {
              clearInterval(id);
              i = 0;
            }
            else {
              hold += width;
              elem.style.width = hold + "%";
              return hold;
            }
          }
        }
      }

      function pause() {
        var elem = document.getElementById("myBar");
        var id = setInterval(frame, 10);
        var hold = 0;
        function frame() {
          elem.style.width = hold + "%";
        }
      }

      function callPlayer(frame_id, func, args) {
        if (window.jQuery && frame_id instanceof jQuery) frame_id = frame_id.get(0).id;
        var iframe = document.getElementById(frame_id);
        if (iframe && iframe.tagName.toUpperCase() != 'IFRAME') {
            iframe = iframe.getElementsByTagName('iframe')[0];
        }
        if (iframe) {
            // Frame exists,
            iframe.contentWindow.postMessage(JSON.stringify({
                "event": "command",
                "func": func,
                "args": args || [],
                "id": frame_id
            }), "*");
        }
      }
    </script>
  </head>
  <body>
    <div id="content">
      <span class="slide">
        <a href="#" onclick="openSlideMenu()">
          <i class="fas fa-bars fa-2x"></i>
        </a>
      </span>
      <div id="menu" class="nav">
        <a href="#" class="close" onclick="closeSlideMenu()">
          <i class="fas fa-times"></i>
        </a>
        <li><a href="#">Home</a></li>
      </div>
      <div class="room-title">
        Room
      </div>
    </div>
    <div class="row">
      <div class="hud-bar">
        <h2 style="font-weight: 100;">
          <i class="fas fa-volume-off"></i>&emsp;Song Title (add dynamically)
        </h2>
      </br>
        <div id="myProgress">
          <div id="myBar"></div>
        </div>
        <div class="song-buttons">
          <button onclick="move(10)"><i class="fas fa-play fa-2x"></i>&ensp;</button>
          <button onclick="pause()"><i class="fas fa-pause fa-2x"></i></button>
          <!-- <a href="javascript:void callPlayer(&quot;whateverID&quot;,&quot;playVideo&quot;)"><i class="fas fa-play"></i></a>
          <a href="javascript:void callPlayer(&quot;whateverID&quot;,&quot;pauseVideo&quot;)"><i class="fas fa-pause"></i></a>
          <div id="whateverID">
            <iframe width="0" height="0" frameborder="0" title="YouTube video player" type="text/html" src="http://www.youtube.com/embed/u1zgFlCw8Aw?enablejsapi=1"></iframe>
          </div> -->
        </div>
        <div class="active-listeners">
          <h4 style="font-weight: 100;">(num) listeners in this room</h4>
        </div>
      </div>
      <div class="column">
        <div class="row">
          <div class="bar-left">
            <div class="content-title">
              Queue
            </div>
          </div>
          <div class="queue">
            <li>this is a very long item to test line breaks in case things go south</li>
            <li>item</li>
            <li>item</li>
            <li>item</li>
          </div>
          </div>
        </div>
      <div class="column">
        <div class="row">
          <div class="bar-right">
            <div class="content-title">
              Recommend song
            </div>
          </div>
          <div class="song-list" style="height: 25px;">
            <div class="bar">
            </div>
            <li>This song is dope</li>
          </div>
          <div class="bar-right">
            <div class="content-title">
              Vote
            </div>
          </div>
          <div class="song-list" style="height: 300px">
            <li><i class="fas fa-check"></i>&ensp;<i class="fas fa-times"></i>&ensp;item</li>
            <li><i class="fas fa-check"></i>&ensp;<i class="fas fa-times"></i>&ensp;item</li>
            <li><i class="fas fa-check"></i>&ensp;<i class="fas fa-times"></i>&ensp;item</li>
            <li><i class="fas fa-check"></i>&ensp;<i class="fas fa-times"></i>&ensp;item</li>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

Sprint 1/polls/templates/polls/roomOld.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Room</title>
    <script src="https://kit.fontawesome.com/72ae810c7a.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="stylesheet.css">
    <script>
      function openSlideMenu() {
        document.getElementById('menu').style.width='250px';
        document.getElementById('content').style.marginLeft='250px';
      }
      function closeSlideMenu() {
        document.getElementById('menu').style.width='0px';
        document.getElementById('content').style.marginLeft='0px';
      }
      var i = 0;
      function move() {
        if (i == 0) {
          i = 1;
          var elem = document.getElementById("myBar");
          var width = 1;
          var id = setInterval(frame, 10);
          function frame() {
            if (width >= 100) {
              clearInterval(id);
              i = 0;
            } else {
              width++;
              elem.style.width = width + "%";
            }
          }
        }
      }
    </script>
  </head>
  <body>
    <div id="content">
      <span class="slide">
        <a href="#" onclick="openSlideMenu()">
          <i class="fas fa-bars fa-2x"></i>
        </a>
      </span>
      <div id="menu" class="nav">
        <a href="#" class="close" onclick="closeSlideMenu()">
          <i class="fas fa-times"></i>
        </a>
        <li><a href="#">Home</a></li>
      </div>
      <div class="room-title">
        Room
      </div>
    </div>
    <div class="hud-bar">
      <h2 style="font-weight: 100;"><i class="fas fa-volume-off"></i>&emsp;Song Title (add dynamically)</h2>
      <div id="myProgress">
        <div id="myBar"></div>
      </div>
      <div class="song-buttons">
        <button onclick="move()"><i class="fas fa-backward fa-2x">&ensp;</i></button>
        <button onclick="move()"><i class="fas fa-play fa-2x"></i>&ensp;</button>
        <button onclick="move()"><i class="fas fa-forward fa-2x"></i></button>
      </div>
      <div class="active-listeners">
        <h4 style="font-weight: 100;">(num) listeners in this room</h4>
      </div>
    </div>
    <div class="queue">
      <div class="bar">
        <div class="content-title">
          Queue
        </div>
      </div>
      <li>this is a very long item to test line breaks in case things go south</li>
      <li>item</li>
      <li>item</li>
      <li>item</li>
    </div>
  </body>
</html>

Sprint 1/polls/templates/polls/roomOld2.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Room</title>
    {% load static %}
    <script src="https://kit.fontawesome.com/72ae810c7a.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'polls/test1.css' %}">
    <!-- <script src="https://kit.fontawesome.com/72ae810c7a.js" crossorigin="anonymous"></script> -->
    <!-- <link rel="stylesheet" href="test1.css"> -->
    <script>
      function openSlideMenu() {
        document.getElementById('menu').style.width='250px';
        document.getElementById('content').style.marginLeft='250px';
      }
      function closeSlideMenu() {
        document.getElementById('menu').style.width='0px';
        document.getElementById('content').style.marginLeft='0px';
      }
      var i = 0;
      function move() {
        if (i == 0) {
          i = 1;
          var elem = document.getElementById("myBar");
          var width = 1;
          var id = setInterval(frame, 10);
          function frame() {
            if (width >= 100) {
              clearInterval(id);
              i = 0;
            } else {
              width++;
              elem.style.width = width + "%";
            }
          }
        }
      }
    </script>
  </head>
  <body>
    <div id="content">
      <span class="slide">
        <a href="#" onclick="openSlideMenu()">
          <i class="fas fa-bars fa-2x"></i>
        </a>
      </span>
      <div id="menu" class="nav">
        <a href="#" class="close" onclick="closeSlideMenu()">
          <i class="fas fa-times"></i>
        </a>
        <li><a href="#">Home</a></li>
      </div>
      <div class="room-title">
        Room
      </div>
    </div>
    <div class="row">
      <div class="hud-bar">
        <h2 style="font-weight: 100;">
          <i class="fas fa-volume-off"></i>&emsp;Song Title (add dynamically)
        </h2>
        <div id="myProgress">
          <div id="myBar"></div>
        </div>
        <div class="song-buttons">
          <button onclick="move()"><i class="fas fa-backward fa-2x">&ensp;</i></button>
          <button onclick="move()"><i class="fas fa-play fa-2x"></i>&ensp;</button>
          <button onclick="move()"><i class="fas fa-forward fa-2x"></i></button>
        </div>
        <div class="active-listeners">
          <h4 style="font-weight: 100;">(num) listeners in this room</h4>
        </div>
      </div>
      <div class="column">
        <div class="row">
          <div class="bar-left">
            <div class="content-title">
              Queue
            </div>
          </div>
          <div class="queue">
            <li>this is a very long item to test line breaks in case things go south</li>
            <li>item</li>
            <li>item</li>
            <li>item</li>
          </div>
          </div>
        </div>

      <div class="column">
        <div class="row">
          <div class="bar-right">
            <div class="content-title">
              Recommend song
            </div>
          </div>
          <div class="song-list" style="height: 25px;">
            <div class="bar">
            </div>
            <li>This song is dope</li>
          </div>
          <div class="bar-right">
            <div class="content-title">
              Vote
            </div>
          </div>
          <div class="song-list" style="height: 300px">
            <li><i class="fas fa-check"></i>&ensp;<i class="fas fa-times"></i>&ensp;item</li>
            <li><i class="fas fa-check"></i>&ensp;<i class="fas fa-times"></i>&ensp;item</li>
            <li><i class="fas fa-check"></i>&ensp;<i class="fas fa-times"></i>&ensp;item</li>
            <li><i class="fas fa-check"></i>&ensp;<i class="fas fa-times"></i>&ensp;item</li>
          </div>
        </div>


      </div>
    </div>


  </body>
</html>